// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import Autocomplete_controller from "./autocomplete_controller"
import Carousel_controller from "./carousel_controller"
import Test_controller from "./test_controller"
import Carousel from "stimulus-carousel"

application.register("carousel", Carousel)
application.register("hello", HelloController)
application.register("autocomplete", Autocomplete_controller)
application.register("carousel1", Carousel_controller)
application.register("car", Test_controller)
